on: [pull_request_review]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Label test
      uses: hphu3/label-pr@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

